version: 2

sources:
  - name: src 
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: nations
      - name: regions
      - name: orders
        config:
          loaded_at_field: "CONVERT_TIMEZONE('UTC', O_ORDERDATE::timestamp)"

          freshness:
            warn_after: {count: 1, period: hour}
            error_after: {count: 2, period: hour}
              
      - name: PARTSUPPS
      - name: suppliers
      - name: parts
      - name: lineitems

     