version: 2

sources:
  - name: src 
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: nations
      - name: regions
      - name: orders
        config:
          loaded_at_field: "O_ORDERDATE::timestamp"
          freshness:
            warn_after: {count: 1, period: day}   # Allows data up to 1 day
            error_after: {count: 2, period: day}
              
      - name: PARTSUPPS
      - name: suppliers
      - name: parts
      - name: lineitems

     